-- =====================================================================
-- Generated by scripts/import-art.mjs on 10/9/2026, 8:46:48 PM
-- 61 images for the "digital-art-graphic-design" gallery.
--
-- Before running: change the titles (2nd value in each row) to the real
-- names of your works, and fix any dates (last value, YYYY-MM-DD) that
-- aren't when you made the piece. Then run in pgAdmin (F5) and restart
-- `npm run dev`.
--
-- Columns: (slug, title, image path, width, height, date made)
-- Safe to run again: existing entries only get their image refreshed;
-- titles and dates you've changed in the database are kept.
-- =====================================================================

BEGIN;

INSERT INTO projects
  (category_id, slug, title, image_url, image_alt, image_width, image_height, completed_on)
SELECT c.id, v.slug, v.title, v.image_url, v.title, v.width, v.height, v.made::date
FROM (VALUES
  ('art-a', 'A', '/images/projects/digital-art/a.webp', 2000, 2000, '2026-10-09'),
  ('art-a1', 'A1', '/images/projects/digital-art/a1.webp', 2000, 885, '2026-10-09'),
  ('art-a2', 'A2', '/images/projects/digital-art/a2.webp', 1414, 2000, '2026-10-09'),
  ('art-b', 'B', '/images/projects/digital-art/b.webp', 1545, 2000, '2026-10-09'),
  ('art-b1', 'B1', '/images/projects/digital-art/b1.webp', 1414, 2000, '2026-10-09'),
  ('art-b2', 'B2', '/images/projects/digital-art/b2.webp', 1414, 2000, '2026-10-09'),
  ('art-c', 'C', '/images/projects/digital-art/c.webp', 1545, 2000, '2026-10-09'),
  ('art-c1', 'C1', '/images/projects/digital-art/c1.webp', 612, 792, '2026-10-09'),
  ('art-c2', 'C2', '/images/projects/digital-art/c2.webp', 1414, 2000, '2026-10-09'),
  ('art-d', 'D', '/images/projects/digital-art/d.webp', 1370, 2000, '2026-10-09'),
  ('art-d1', 'D1', '/images/projects/digital-art/d1.webp', 2000, 1125, '2026-10-09'),
  ('art-d2', 'D2', '/images/projects/digital-art/d2.webp', 1414, 2000, '2026-10-09'),
  ('art-e', 'E', '/images/projects/digital-art/e.webp', 1594, 2000, '2026-10-09'),
  ('art-e1', 'E1', '/images/projects/digital-art/e1.webp', 1920, 1080, '2026-10-09'),
  ('art-e2', 'E2', '/images/projects/digital-art/e2.webp', 1414, 2000, '2026-10-09'),
  ('art-f', 'F', '/images/projects/digital-art/f.webp', 1117, 1295, '2026-10-09'),
  ('art-f1', 'F1', '/images/projects/digital-art/f1.webp', 2000, 1050, '2026-10-09'),
  ('art-f2', 'F2', '/images/projects/digital-art/f2.webp', 1415, 2000, '2026-10-09'),
  ('art-g', 'G', '/images/projects/digital-art/g.webp', 1917, 2000, '2026-10-09'),
  ('art-g1', 'G1', '/images/projects/digital-art/g1.webp', 2000, 1414, '2026-10-09'),
  ('art-g2', 'G2', '/images/projects/digital-art/g2.webp', 1415, 2000, '2026-10-09'),
  ('art-h', 'H', '/images/projects/digital-art/h.webp', 1500, 2000, '2026-10-09'),
  ('art-h1', 'H1', '/images/projects/digital-art/h1.webp', 2000, 1414, '2026-10-09'),
  ('art-h2', 'H2', '/images/projects/digital-art/h2.webp', 1419, 2000, '2026-10-09'),
  ('art-i', 'I', '/images/projects/digital-art/i.webp', 1545, 2000, '2026-10-09'),
  ('art-i1', 'I1', '/images/projects/digital-art/i1.webp', 2000, 1414, '2026-10-09'),
  ('art-i2', 'I2', '/images/projects/digital-art/i2.webp', 2000, 1125, '2026-10-09'),
  ('art-j', 'J', '/images/projects/digital-art/j.webp', 1500, 2000, '2026-10-09'),
  ('art-j1', 'J1', '/images/projects/digital-art/j1.webp', 2000, 1125, '2026-10-09'),
  ('art-j2', 'J2', '/images/projects/digital-art/j2.webp', 2000, 1125, '2026-10-09'),
  ('art-k', 'K', '/images/projects/digital-art/k.webp', 1500, 2000, '2026-10-09'),
  ('art-k1', 'K1', '/images/projects/digital-art/k1.webp', 1600, 2000, '2026-10-09'),
  ('art-l', 'L', '/images/projects/digital-art/l.webp', 1998, 2000, '2026-10-09'),
  ('art-l1', 'L1', '/images/projects/digital-art/l1.webp', 1567, 1959, '2026-10-09'),
  ('art-m', 'M', '/images/projects/digital-art/m.webp', 1997, 2000, '2026-10-09'),
  ('art-m1', 'M1', '/images/projects/digital-art/m1.webp', 2000, 1214, '2026-10-09'),
  ('art-n', 'N', '/images/projects/digital-art/n.webp', 2000, 1999, '2026-10-09'),
  ('art-n1', 'N1', '/images/projects/digital-art/n1.webp', 2000, 1000, '2026-10-09'),
  ('art-o', 'O', '/images/projects/digital-art/o.webp', 1390, 2000, '2026-10-09'),
  ('art-o1', 'O1', '/images/projects/digital-art/o1.webp', 1600, 2000, '2026-10-09'),
  ('art-p', 'P', '/images/projects/digital-art/p.webp', 2000, 1419, '2026-10-09'),
  ('art-p1', 'P1', '/images/projects/digital-art/p1.webp', 1080, 1350, '2026-10-09'),
  ('art-q', 'Q', '/images/projects/digital-art/q.webp', 2000, 1390, '2026-10-09'),
  ('art-q1', 'Q1', '/images/projects/digital-art/q1.webp', 2000, 1125, '2026-10-09'),
  ('art-r', 'R', '/images/projects/digital-art/r.webp', 1419, 2000, '2026-10-09'),
  ('art-r1', 'R1', '/images/projects/digital-art/r1.webp', 2000, 1125, '2026-10-09'),
  ('art-s', 'S', '/images/projects/digital-art/s.webp', 1545, 2000, '2026-10-09'),
  ('art-t', 'T', '/images/projects/digital-art/t.webp', 2000, 1214, '2026-10-09'),
  ('art-t1', 'T1', '/images/projects/digital-art/t1.webp', 1395, 2000, '2026-10-09'),
  ('art-u', 'U', '/images/projects/digital-art/u.webp', 1600, 2000, '2026-10-09'),
  ('art-u1', 'U1', '/images/projects/digital-art/u1.webp', 2000, 1125, '2026-10-09'),
  ('art-v', 'V', '/images/projects/digital-art/v.webp', 1600, 2000, '2026-10-09'),
  ('art-v1', 'V1', '/images/projects/digital-art/v1.webp', 2000, 1125, '2026-10-09'),
  ('art-w', 'W', '/images/projects/digital-art/w.webp', 2000, 1600, '2026-10-09'),
  ('art-w1', 'W1', '/images/projects/digital-art/w1.webp', 2000, 1125, '2026-10-09'),
  ('art-x', 'X', '/images/projects/digital-art/x.webp', 2000, 1600, '2026-10-09'),
  ('art-x1', 'X1', '/images/projects/digital-art/x1.webp', 1414, 2000, '2026-10-09'),
  ('art-y', 'Y', '/images/projects/digital-art/y.webp', 2000, 1123, '2026-10-09'),
  ('art-y1', 'Y1', '/images/projects/digital-art/y1.webp', 1414, 2000, '2026-10-09'),
  ('art-z', 'Z', '/images/projects/digital-art/z.webp', 1500, 2000, '2026-10-09'),
  ('art-z1', 'Z1', '/images/projects/digital-art/z1.webp', 2000, 1414, '2026-10-09')
) AS v (slug, title, image_url, width, height, made)
JOIN project_categories c ON c.slug = 'digital-art-graphic-design'
ON CONFLICT (slug) DO UPDATE SET
  image_url    = EXCLUDED.image_url,
  image_width  = EXCLUDED.image_width,
  image_height = EXCLUDED.image_height;

COMMIT;
