import type { PortfolioData } from "./types";

/**
 * Sample content used only when PostgreSQL can't be reached, so the layout
 * still renders while you set things up. It mirrors db/seed.sql.
 * Your real content lives in the database, not here.
 */
export const fallbackData: PortfolioData = {
  profile: {
    fullName: "Zach Jacob T. Feldan",
    displayName: "Zach Jacob",
    headline: "Multimedia professional moving into IT",
    bio: "I lead multimedia for institution-wide events at the Communications Bureau of UST General Santos, and I'm a first-year MSIT student at Ateneo de Davao. I design, illustrate and animate, and I'm now building database-backed web apps with PostgreSQL and the PERN stack.",
    portraitUrl: null,
    location: "General Santos City, Philippines",
    email: "you@example.com",
    resumeUrl: null,
  },
  projects: [
    {
      id: 1,
      slug: "portfolio-website",
      title: "This portfolio",
      summary: "Next.js, Tailwind CSS and PostgreSQL, built and documented from scratch.",
      category: "it",
      coverUrl: null,
      coverAlt: null,
      projectUrl: null,
      repoUrl: null,
      isFeatured: true,
      skills: ["Next.js", "PostgreSQL", "Tailwind CSS"],
    },
    {
      id: 2,
      slug: "davao-marketplace-pipeline",
      title: "Davao Digital Marketplace data pipeline",
      summary: "S3 ingestion into Aurora PostgreSQL, then DynamoDB and Glue, built for MSIT Data Management.",
      category: "it",
      coverUrl: null,
      coverAlt: null,
      projectUrl: null,
      repoUrl: null,
      isFeatured: true,
      skills: ["AWS", "PostgreSQL"],
    },
    {
      id: 3,
      slug: "undergrad-capstone",
      title: "Undergraduate capstone",
      summary: "A PostgreSQL-backed system. Replace this with the problem it solved and your role.",
      category: "it",
      coverUrl: null,
      coverAlt: null,
      projectUrl: null,
      repoUrl: null,
      isFeatured: false,
      skills: ["PostgreSQL"],
    },
    {
      id: 4,
      slug: "paskuhan-opening-video",
      title: "Paskuhan opening video",
      summary: "Animated opening for UST General Santos' Paskuhan celebration.",
      category: "creative",
      coverUrl: null,
      coverAlt: null,
      projectUrl: null,
      repoUrl: null,
      isFeatured: false,
      skills: ["After Effects", "Illustrator"],
    },
    {
      id: 5,
      slug: "event-coverage",
      title: "Institution-wide event coverage",
      summary: "Photo and video documentation for the Communications Bureau.",
      category: "creative",
      coverUrl: null,
      coverAlt: null,
      projectUrl: null,
      repoUrl: null,
      isFeatured: false,
      skills: ["Photoshop"],
    },
    {
      id: 6,
      slug: "game-art",
      title: "Game art direction",
      summary: "Visual lead work for a US-based game studio.",
      category: "creative",
      coverUrl: null,
      coverAlt: null,
      projectUrl: null,
      repoUrl: null,
      isFeatured: false,
      skills: ["Photoshop", "Illustrator"],
    },
  ],
  skills: [
    { id: 1, slug: "postgresql", name: "PostgreSQL", category: "database", proficiency: 3, iconKey: "database", iconUrl: null },
    { id: 2, slug: "mysql", name: "MySQL", category: "database", proficiency: 3, iconKey: "database", iconUrl: null },
    { id: 3, slug: "react", name: "React", category: "web", proficiency: 2, iconKey: "code", iconUrl: null },
    { id: 4, slug: "nodejs", name: "Node.js", category: "web", proficiency: 2, iconKey: "server", iconUrl: null },
    { id: 5, slug: "nextjs", name: "Next.js", category: "web", proficiency: 1, iconKey: "layers", iconUrl: null },
    { id: 6, slug: "tailwind", name: "Tailwind CSS", category: "web", proficiency: 1, iconKey: "code", iconUrl: null },
    { id: 7, slug: "aws", name: "AWS", category: "cloud", proficiency: 1, iconKey: "cloud", iconUrl: null },
    { id: 8, slug: "photoshop", name: "Photoshop", category: "design", proficiency: 4, iconKey: "image", iconUrl: null },
    { id: 9, slug: "illustrator", name: "Illustrator", category: "design", proficiency: 4, iconKey: "pen", iconUrl: null },
    { id: 10, slug: "indesign", name: "InDesign", category: "design", proficiency: 4, iconKey: "layers", iconUrl: null },
    { id: 11, slug: "after-effects", name: "After Effects", category: "motion", proficiency: 2, iconKey: "film", iconUrl: null },
  ],
  certificates: [],
  experiences: [
    {
      id: 1,
      role: "Support Staff, Multimedia",
      organization: "Communications Bureau, UST General Santos",
      location: "General Santos City",
      startDate: "2025-01-01",
      endDate: null,
      summary: null,
      highlights: [
        "Lead multimedia output for institution-wide events",
        "Coordinate coverage and documentation with the Bureau director",
        "Train student volunteers in design and media",
      ],
    },
    {
      id: 2,
      role: "Visual Lead",
      organization: "Game development studio (US, remote)",
      location: null,
      startDate: "2024-01-01",
      endDate: "2024-12-31",
      summary: null,
      highlights: ["Led visual direction for game art", "Worked with a remote team across time zones"],
    },
  ],
  education: [
    {
      id: 1,
      degree: "Master of Science in Information Technology",
      school: "Ateneo de Davao University",
      startYear: 2026,
      endYear: null,
      status: "in_progress",
      details: null,
    },
    {
      id: 2,
      degree: "Your bachelor's degree",
      school: "Your university",
      startYear: null,
      endYear: 2024,
      status: "completed",
      details: "Major in databases",
    },
  ],
  socials: [
    { id: 1, platform: "github", label: "GitHub", url: "https://github.com/your-username", iconKey: "github" },
    { id: 2, platform: "linkedin", label: "LinkedIn", url: "https://www.linkedin.com/in/your-username", iconKey: "linkedin" },
    { id: 3, platform: "behance", label: "Behance", url: "https://www.behance.net/your-username", iconKey: "behance" },
  ],
};
