import type { PortfolioData } from "./types";

/**
 * Sample content used only when PostgreSQL can't be reached, so the layout
 * still renders while you set things up. It mirrors db/seed.sql.
 * Your real content lives in the database, not here.
 */
export const fallbackData: PortfolioData = {
  profile: {
    fullName: "Zach Jacob T. Feldan",
    displayName: "Zach Jacob",
    headline: "Multimedia | IT",
    bio: "I handle multimedia for the Communications Bureau of UST General Santos and I'm a first-year MSIT student at Ateneo de Davao. I design, illustrate and animate, and I'm learning to build web-based apps.",
    portraitUrl: null,
    location: "General Santos City, Philippines",
    email: "you@example.com",
    resumeUrl: null,
  },
  categories: [
    {
      id: 1,
      slug: "graphic-design",
      name: "Graphic Design",
      iconKey: "palette",
      coverUrl: null,
      projects: [
        {
          id: 5,
          slug: "event-pubmats",
          title: "Event publication materials",
          description: "Replace this with what the series was for and what you made.",
          imageUrl: null,
          imageAlt: null,
          projectUrl: null,
          completedOn: "2025-11-15",
          tools: [{ name: "Photoshop", iconKey: "text:Ps", iconUrl: null }, { name: "Illustrator", iconKey: "text:Ai", iconUrl: null }],
        },
      ],
    },
    {
      id: 2,
      slug: "web-development",
      name: "Web Development",
      iconKey: "code",
      coverUrl: null,
      projects: [
        {
          id: 1,
          slug: "portfolio-website",
          title: "This portfolio",
          description: "Next.js, Tailwind CSS and PostgreSQL, built and documented from scratch.",
          imageUrl: null,
          imageAlt: null,
          projectUrl: null,
          completedOn: "2026-10-01",
          tools: [{ name: "PostgreSQL", iconKey: "si:postgresql", iconUrl: null }, { name: "Next.js", iconKey: "si:nextjs", iconUrl: null }, { name: "Tailwind CSS", iconKey: "code", iconUrl: null }],
        },
        {
          id: 2,
          slug: "davao-marketplace-pipeline",
          title: "Davao Digital Marketplace data pipeline",
          description: "S3 ingestion into Aurora PostgreSQL, then DynamoDB and Glue, built for MSIT Data Management.",
          imageUrl: null,
          imageAlt: null,
          projectUrl: null,
          completedOn: "2026-09-20",
          tools: [{ name: "PostgreSQL", iconKey: "si:postgresql", iconUrl: null }, { name: "AWS", iconKey: "cloud", iconUrl: null }],
        },
        {
          id: 3,
          slug: "undergrad-capstone",
          title: "Undergraduate capstone",
          description: "Replace this with the problem it solved and your role.",
          imageUrl: null,
          imageAlt: null,
          projectUrl: null,
          completedOn: "2024-05-01",
          tools: [{ name: "PostgreSQL", iconKey: "si:postgresql", iconUrl: null }],
        },
      ],
    },
    {
      id: 3,
      slug: "digital-illustration",
      name: "Digital Illustration",
      iconKey: "pen",
      coverUrl: null,
      projects: [
        {
          id: 6,
          slug: "game-art",
          title: "Game art direction",
          description: "Visual lead work for a US-based game studio.",
          imageUrl: null,
          imageAlt: null,
          projectUrl: null,
          completedOn: "2024-08-01",
          tools: [{ name: "Photoshop", iconKey: "text:Ps", iconUrl: null }, { name: "Illustrator", iconKey: "text:Ai", iconUrl: null }],
        },
      ],
    },
    {
      id: 4,
      slug: "motion-graphics",
      name: "Motion Graphics",
      iconKey: "film",
      coverUrl: null,
      projects: [
        {
          id: 4,
          slug: "paskuhan-opening-video",
          title: "Paskuhan opening video",
          description: "Animated opening for UST General Santos' Paskuhan celebration.",
          imageUrl: null,
          imageAlt: null,
          projectUrl: null,
          completedOn: "2026-09-30",
          tools: [{ name: "Illustrator", iconKey: "text:Ai", iconUrl: null }, { name: "After Effects", iconKey: "text:Ae", iconUrl: null }],
        },
      ],
    },
    {
      id: 5,
      slug: "digital-assets",
      name: "Digital Assets",
      iconKey: "layers",
      coverUrl: null,
      projects: [],
    },
  ],
  skills: [
    { id: 1, slug: "html", name: "HTML", category: "web", proficiency: 3, iconKey: "si:html5", iconUrl: null },
    { id: 2, slug: "css", name: "CSS", category: "web", proficiency: 3, iconKey: "si:css", iconUrl: null },
    { id: 3, slug: "react", name: "React", category: "web", proficiency: 1, iconKey: "si:react", iconUrl: null },
    { id: 4, slug: "nextjs", name: "Next.js", category: "web", proficiency: 1, iconKey: "si:nextjs", iconUrl: null },
    { id: 5, slug: "photoshop", name: "Photoshop", category: "design", proficiency: 5, iconKey: "text:Ps", iconUrl: null },
    { id: 6, slug: "clip-studio", name: "Clip Studio", category: "design", proficiency: 5, iconKey: "text:CSP", iconUrl: null },
    { id: 7, slug: "procreate", name: "Procreate", category: "design", proficiency: 5, iconKey: "text:Pc", iconUrl: null },
    { id: 8, slug: "illustrator", name: "Illustrator", category: "design", proficiency: 5, iconKey: "text:Ai", iconUrl: null },
    { id: 9, slug: "inkscape", name: "Inkscape", category: "design", proficiency: 5, iconKey: "si:inkscape", iconUrl: null },
    { id: 10, slug: "indesign", name: "InDesign", category: "design", proficiency: 3, iconKey: "text:Id", iconUrl: null },
    { id: 11, slug: "after-effects", name: "After Effects", category: "motion", proficiency: 1, iconKey: "text:Ae", iconUrl: null },
    { id: 12, slug: "postgresql", name: "PostgreSQL", category: "database", proficiency: 3, iconKey: "si:postgresql", iconUrl: null },
  ],
  certificates: [],
  experiences: [
    {
      id: 1,
      role: "Support Staff, Multimedia",
      organization: "Communications Bureau, UST General Santos",
      location: "General Santos City",
      startDate: "2025-01-01",
      endDate: null,
      summary: null,
      highlights: [
        "Lead multimedia output for institution-wide events",
        "Coordinate coverage and documentation with the Bureau director",
        "Train student volunteers in design and media",
      ],
    },
    {
      id: 2,
      role: "Visual Lead",
      organization: "Game development studio (US, remote)",
      location: null,
      startDate: "2024-01-01",
      endDate: "2024-12-31",
      summary: null,
      highlights: ["Led visual direction for game art", "Worked with a remote team across time zones"],
    },
  ],
  education: [
    {
      id: 1,
      degree: "Master of Science in Information Technology",
      school: "Ateneo de Davao University",
      startYear: 2026,
      endYear: null,
      status: "in_progress",
      details: null,
    },
    {
      id: 2,
      degree: "Your bachelor's degree",
      school: "Your university",
      startYear: null,
      endYear: 2024,
      status: "completed",
      details: "Major in databases",
    },
  ],
  socials: [
    { id: 1, platform: "github", label: "GitHub", url: "https://github.com/your-username", iconKey: "github" },
    { id: 2, platform: "linkedin", label: "LinkedIn", url: "https://www.linkedin.com/in/your-username", iconKey: "linkedin" },
    { id: 3, platform: "behance", label: "Behance", url: "https://www.behance.net/your-username", iconKey: "behance" },
  ],
};
